### PR TITLE
python: added missing Python bindings.

### PR DESCRIPTION
**Pull request by cristi-iacob**
Added the missing Python bindings. More details about these can be found in this [discussion](https://github.com/analogdevicesinc/libiio/issues/365).

Signed-off-by: Cristi Iacob <cristian.iacob@analog.com>

### CODE REVIEW

**Comment by rgetz** [comment]
https://app.codacy.com/gh/analogdevicesinc/libiio/pullRequest?prid=5393691

**Comment by rgetz** [comment]
tip : if you add the issue number #443 , it will automatically link things,

https://guides.github.com/features/issues/#notifications

**Comment by rgetz** [comment]
I ran the script in the issue on the branch, I get:

```
0 iio_create_xml_context_mem
0 iio_context_get_attr_value
0 iio_context_find_device
0 iio_device_find_channel
0 iio_device_find_attr
0 iio_device_find_buffer_attr
0 iio_device_set_data
0 iio_device_get_data
0 iio_channel_find_attr
0 iio_channel_set_data
0 iio_buffer_first
0 iio_buffer_foreach_sample
0 iio_buffer_set_data
0 iio_channel_convert_inverse
0 iio_device_find_debug_attr
0 iio_device_identify_filename
```
which is much less - thanks.

If we add these names in a comment in any file in that directory, (even a the doc directory), it will not show up...

slight tweak to look in all files, and doc directory.

```
for funct in $(grep ^__api iio.h | tr " " "\n" | grep "(" | sed 's/(.*$//' | grep -v -e _bool$ -e _double$ -e _longlong$ -e _all$ -e _raw$);    do echo "$(grep -c -R $funct ./bindings/python/* | awk -F: '{sum += $2} END {print sum}') $funct" ;   done | grep "^0"
```

**Comment by cristi-iacob** [comment]
I have corrected the lines with codacy-issues, but it seems that the issue I told you about [here](https://github.com/analogdevicesinc/libiio/pull/434#discussion_r409533673) still persists.

Should I add a (hidden) file or comment containing the name of the missing bindings? If yes, where should I add them?

**Comment by cristi-iacob** [comment]
I have managed to avoid this behavior of Codacy. I have added a new commit containing the modifications requested by Codacy. The strange thing is that if I squash these 2 commits, Codacy reports the issues again. Exactly the same happens on the codacy-test branch (#446), which is the one I have made by copy-paste-ing the iio.py file.

**Comment by rgetz** [comment]
I would add the on purpose  un-implemented functions into the doc (rst) in a separate section. Or make a list of C to python equivalents, and just put the python equivalents of these functions. 

@tfcollins : any thoughts?

**Comment by tfcollins** [comment]
If you have a list of non-implemented functions sure. A mapping between the C and python I think is a bit overkill since they are used in different ways. With the python API you can do autodiscovery of the functions by just using it and not looking at the doc

**Pull request merged**
