### PR TITLE
python: Fixes --samples argument by multiplying num_samples by sample_size

### LINKED ISSUE #714: examples/iio_readdev.py: --samples argument selects number of bytes instead of number of samples
--samples argument selects a number of bytes instead of a number of samples like the c version of the app.  

It would be nice to have a working example on how to iterate through samples instead of bytes

```
$ python3 libiio/bindings/python/examples/iio_readdev.py -u ip:192.168.0.29 -s 2 ads1246 | hexdump
0000000 ffff                                   
0000002
```

```
$ iio_readdev -u ip:192.168.0.29 -s 2 ads1246 | hexdump
0000000 ffff 007f 0001 0000 8953 42b6 29fa 1691
0000010 ff7f 007f 8953 42b6 e236 431a 29fa 1691
0000020
```

libiio version:

```
$ python3 libiio/bindings/python/examples/iio_info.py --uri ip:192.168.0.29
IIO context created: network
Backend version: 0.21 (git tag: 48e5852
...
```

### PR DESCRIPTION
**Pull request by jcormier**
Fixes #714

### CODE REVIEW

**Comment by tfcollins** [comment]
Please sign your commits so they show: `Signed-off-by:`

**Comment by jcormier** [comment]
Done, I even digitally signed it :D

**Comment by jcormier** [comment]
Fixed samples typo...

**Review by tfcollins — APPROVED** [review]

**Comment by pcercuei** [comment]
Merged, thanks!

**Pull request merged**
