### PR TITLE
sorting: Use old sorting algorithm for channels

### PR DESCRIPTION
**Pull request by adisuciu**
This algorithm should be backwards compatible

Signed-off-by: Adrian Suciu <adrian.suciu@analog.com>

### CODE REVIEW

**Comment by pcercuei** [comment]
I think it is OK as it is now, the apps should not rely on the sorting of the channels or attributes, but rather use iio_device_find_channel.

**Comment by mhennerich** [comment]
No - it's still broken -
The issue is that remote via IIOD and local share a channel enable mask. If channel sorting on both ends is done differently things fail, since the bits set doesn’t correspond to the same channels. 
If we want to maintain backwards compatibility I see no way around reverting the channel sorting completely.

**Comment by mhennerich** [comment]
Hi @pcercuei,

Do you see a way of fixing this while maintaining backward compatibility?

**Comment by pcercuei** [comment]
Ah, right. I don't think there's an easy way to fix this then. The revert would be the proper solution.

**Pull request merged**
