### PR TITLE
Enhance buffer API

### PR DESCRIPTION
**Pull request by rofferom**
Implements buffer API enhancement discussed in issue #16

### CODE REVIEW

**Comment by pcercuei** [comment]
Hi,

I still have some comments before I merge this. I will embed the comments in your commits, that will be simpler.

Also, please add your Signed-Off-By in the commit messages, and rename the "add iio_device_set_nb_buffers" commit message to reflect the new function name.

Thanks!

**Comment by rofferom** [comment]
Ok, tell me when you have terminated your review and I will update my commits

**Comment by pcercuei** [comment]
Ok, I think I'm done :)

One last comment: please decouple the commits that add API functions to the ones that modify the local backend; e.g. first add iio_buffer_get_poll_fd( ) in one commit, then the backend function in a second one. This makes things easier for me when tracking changes and issues.

Thanks for your hard work!

**Comment by rofferom** [comment]
New version pushed !

About https://github.com/Parrot-Developers/libiio/commit/95a67789042a1cc4a0f3a119a6f811f2c05bdb7f#commitcomment-11926460, I don't understand why it would crash, there can be some free(NULL) calls but it is allowed by free() function. Or did I miss something ?

**Comment by pcercuei** [comment]
You're right, I didn't know that free(NULL) was allowed.

However I noticed real mistakes in the last commit:
 * you don't free pdata->blocks and pdata->addrs in enable_high_speed( ) in the case where an error happens in the rest of the function; they will eventually be freed but it would be better to free them sooner (as they won't be used anyway).
 * you reset pdata->nb_blocks to 0. Then, enable_high_speed( ) will exit with an error code, which will make local_open( ) revert to the low-speed interface, and set a buffer size of 0. You should not reset pdata->nb_blocks at all.
 * You free pdata->blocks and pdata->addrs in local_shutdown( ), and not in local_close( ), so you will leak memory if you open/close the device multiple times in one session.

**Comment by rofferom** [comment]
You're right, I should have been more cautious with my commits... Here is a new version that fixes what you have mentioned

**Comment by pcercuei** [comment]
There is a "return -errno" in local.c:712 that should jump to the end of the function, so that pdata->blocks and pdata->addrs are freed. The rest looks good to me.

Almost there :)

**Comment by rofferom** [comment]
Last version seems to build, but push artifact operation has failed : *Error pushing artifact: The operation has timed out*

**Comment by pcercuei** [comment]
The appveyor build failed but it's because appveyor is crap :)

I will do one last round of reviews in the next couple of days, to make sure that it doesn't break anything - and I'll merge it by the end of the week.

Thanks!

**Comment by rofferom** [comment]
Ok, thank you !

**Comment by pcercuei** [comment]
Merged. Thanks!

**Pull request merged**
