### PR TITLE
python: code quality improvements

### PR DESCRIPTION
**Pull request by cristi-iacob**
Code quality improvements, accordingly to Codacy.

### CODE REVIEW

**Comment by rgetz** [comment]
Looks like a good start. Thanks.

image

Can you have a look at:
image

seems to be an issue in both readdev.py and writedev.py

**Comment by cristi-iacob** [comment]
I have solved the import signal issue.

**Comment by rgetz** [comment]
One last issue...

According to PEP8, if any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None, and an explicit return statement should be present at the end of the function (if reachable)

This is flagged in iio_info.py in the _handle_context(): function.

**Comment by rgetz** [comment]
I think you messed up the rebase - it includes some things that are already on master.

**Comment by rgetz** [comment]
If you can focus on the examples - I already have a branch for the actual iio.py fixes. (at least from a linter perspective).

I will see if I can finish what I'm working on, and get back to that tomorrow.

**Comment by tfcollins** [comment]
Need to ignore W0212. Otherwise the bindings would probably have to be rearchitected

**Comment by cristi-iacob** [comment]
I removed the commit with the modifications from iio.py and rebased the branch with the current master.

**Comment by rgetz** [comment]
RemarkLint has two issues:
 - [heading-increment] Heading levels should increment by one level at a time (line 15)
 - [fenced-code-flag] Missing code language flag (line 22) should be ` ```shell` (like in README_BUILD.md)

**Comment by dNechita** [comment]
Is there any more work needed to be done here? @cristi-iacob

**Comment by cristi-iacob** [comment]
@dNechita no, it's all done.

**Comment by cristi-iacob** [comment]
The issues from RemarkLink are resolved in #483.

**Comment by dNechita** [comment]
@tfcollins is this ok to merge?

**Comment by rgetz** [comment]
In discussion with @cristi-iacob ; he indicated that the python examples are being re-written in a more pythonic way; and this was close to being finished. (within a week or less).

It doesn't make sense to churn this with these fixes, and then replace things completely in a few days.

**Comment by dNechita** [comment]
> In discussion with @cristi-iacob ; he indicated that the python examples are being re-written in a more pythonic way; and this was close to being finished. (within a week or less).
> 
> It doesn't make sense to churn this with these fixes, and then replace things completely in a few days.

If this PR isn't required, @cristi-iacob please close it.

**Pull request closed without merging**
