### PR TITLE
Fixes #303 and #302

### LINKED ISSUE #303: printf types in dummy-iiostream example not platform independent
The examples/dummy-iiostream.c printf types are not platform independent, and do generate compilation error in the armhf architecture, as in the BeagleBone.

### PR DESCRIPTION
**Pull request by dimasad**
Fixes to the dummy-iiostream example.

### CODE REVIEW

**Comment by rgetz** [comment]
Couple comments 

- we always use signed-off-by on commits (this will need to be added). to the first commit.

- int64_t is guaranteed by the C99 standard to be exactly 64 bits wide, long long normally is, but not always - and can cause problems in some places in this codebase. As long as your compiler supports C99, I don't know why this is necessary. To be truly portable - we should be using the Format macro constants, so it would look like: 
```
uint64_t t;
printf("%" PRIu64 "\n", t);
```

-Robin

**Comment by dimasad** [comment]
I used long long because it is guaranteed to be *at least* 64 bits wide, which is enough to prevent overflow. I was using gcc on the BeagleBone Black, and the specifier "%ld" with int64_t did not work. In that architecture, a long is 32 bits and overflow occurs.

Anyways, format macros can lead to a more elegant solution. I'll change that and add the sign-off.

**Comment by mhennerich** [comment]
Can you please add your signed-of-by tag to the commit message and then push again?
Without we can't merge this PR.

**Comment by dimasad** [comment]
Sorry, I totally forgot about this. Will have time to do this Friday 2019-11-29.

**Comment by dimasad** [comment]
> To be truly portable - we should be using the Format macro constants, so it would look like:
> 
> ```
> uint64_t t;
> printf("%" PRIu64 "\n", t);
> ```

@rgetz, I updated to your truly portable solution.

**Comment by pcercuei** [comment]
Just a nitpick - you use ```PRI "i" 16``` and ```PRI "d" 64```, both variants are fine, but you could use the same one to be consistent :)

**Comment by dimasad** [comment]
> Just a nitpick - you use `PRI "i" 16` and `PRI "d" 64`, both variants are fine, but you could use the same one to be consistent :)

Well, I also am very OCD about these things. Anyways, the previous coder of the example used both `%i` and `%d`. So what I did was replace all `%d` with `PRIdXX` and `%i` with `PRIiXX`. Do you still want me to change it or is my choice reasonable enough?

**Comment by pcercuei** [comment]
Up to you.

**Comment by dimasad** [comment]
I would rather just leave it like it is then.

**Pull request merged**
