### PR TITLE
README.md: remove OS X El Capitan (10.11) from readme

### PR DESCRIPTION
**Pull request by commodo**
Given that suport for Xcode 11 is being added, maybe it's a good idea to
drop support for Xcode 9.

The readme file also contained a left-over for Xcode8 (OS X 10.10) which
was removed a while back. This was removed with this change.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>

### CODE REVIEW

**Comment by commodo** [comment]
for the PR, I'll add a RFC tag;
mostly to highlight that this is a proposal in the form of a PR;

**Comment by rgetz** [comment]
macOS 10.12 (xcode 9) is still supported by MathWorks - who uses libiio; so we need to continue to support things.

https://www.mathworks.com/support/requirements/matlab-system-requirements.html
macOS Mojave (10.14)
macOS High Sierra (10.13)
macOS Sierra (10.12)

When they drop it - we can drop it.

**Comment by commodo** [comment]
> When they drop it - we can drop it.

ack;
then i'll go for plan B; cleanup the README.md [remove macOS Sierra (10.12)] ; since it was forgotten there

**Comment by commodo** [comment]
> > When they drop it - we can drop it.
> 
> ack;
> then i'll go for plan B; cleanup the README.md [remove macOS Sierra (10.12)] ; since it was forgotten there

i wrote the above stuff before coffee;
i'll remove `OS X El Capitan (v 10.11)` from the README list

**Comment by commodo** [comment]
Changelog v1 -> v2:
* don't drop Xcode9
* update readme & PR with commit `README.md: remove OS X El Capitan (10.11) from readme
`

**Comment by commodo** [comment]
Changelog v2 -> v3:
* fix alternative download link for OS X High Sierra; goofed when added Xcode11 and change that to OS 10.14.4 (from 10.13.6)

**Pull request merged**
