### PR TITLE
add note about triggered buffers in dox source

### PR DESCRIPTION
**Pull request by rgetz**
add doc on triggered buffers needed triggers set up.

Signed-off-by: Robin Getz <robin.getz@analog.com>

### CODE REVIEW

**Comment by rgetz** [comment]
doc request as part of #185

**Comment by commodo** [comment]
[LGTM](https://i.pinimg.com/564x/0c/95/0e/0c950ef32237ba7bce66c585a26ebd76.jpg)

**Comment by commodo** [comment]
Will merge this later today if no objections

**Comment by pcercuei** [comment]
Does the doc define what is a "triggered buffer"?

**Comment by rgetz** [comment]
There is a section on triggers above in the doc.

https://github.com/analogdevicesinc/libiio/blob/master/mainpage.dox#L110

If you want me to expand on that - I can try.

-Robin

**Comment by pcercuei** [comment]
Ok. I just find the "triggered buffers" wording strange. Shouldn't it be "triggered device"?

**Pull request merged**
