### PR TITLE
libini added as a submodule and compiled/linked directly into libiio.

### PR DESCRIPTION
**Pull request by matejk**
Signed-off-by: Matej Kenda <matejken@gmail.com>

Done in a similar way as it is done for wingetopt.

Related to #403.

### CODE REVIEW

**Comment by mhennerich** [comment]
Let's wait for @pcercuei comments here...

The options are:
1) Add copy of libini to libiio (my preference)
2) Fork libini fix the cmake issue
3) Fix libini upstream
3) This patch 

-Michael

**Comment by matejk** [comment]
This PR was not intended to fix libini CMake build but to simplify build of libiio.

**Comment by pcercuei** [comment]
What's the issue with upstream libini?

I have no problem if libini is added as a submodule, it would probably be a good idea since it's not packaged anywhere.

**Comment by rgetz** [comment]
Issue with upstream libini is discussed at #403 

It's not a big deal - it's just a matter if you wanted to maintain this in your personal repo forever (as long as people are using libiio), or if it should be moved somewhere else?

-Robin

**Comment by rgetz** [comment]
I opened #428 - I think it's the way to go.

**Comment by rgetz** [comment]
I will close this, unmerged, as it looks like #428 will be merged instead.

**Pull request closed without merging**
