### PR TITLE
appveyor: install graphviz

### PR DESCRIPTION
**Pull request by rgetz**
For some reason, cmake in appveyor is failing since it can't find dot; so install it.

Signed-off-by: Robin Getz <robin.getz@analog.com>

### CODE REVIEW

**Comment by rgetz** [comment]
yeah, this is still failing, so this is not Ok to merge yet.
```
315 installing mingw-w64-i686-graphviz...
316Warning: Could not load "C:\msys64\mingw32\bin\libgvplugin_neato_layout-6.dll" - The specified module could not be found.
```

and then finally:
```
CMake Warning at C:/msys64/mingw32/share/cmake-3.12/Modules/FindDoxygen.cmake:434 (message):
377  Unable to determine doxygen version: Exit code 0xc000007b
378
379Call Stack (most recent call first):
380  C:/msys64/mingw32/share/cmake-3.12/Modules/FindDoxygen.cmake:592 (_Doxygen_find_doxygen)
381  CMakeLists.txt:355 (find_package)
382
383
384-- Found Doxygen: C:/msys64/mingw32/bin/doxygen.exe (found version "") found components:  doxygen dot 
385CMake Error at C:/msys64/mingw32/share/cmake-3.12/Modules/FindDoxygen.cmake:671 (message):
386  Unable to generate Doxyfile template: Exit code 0xc000007b
387
388Call Stack (most recent call first):
389  CMakeLists.txt:355 (find_package)
390
391
392-- Configuring incomplete, errors occurred!
393See also "C:/projects/libiio/build-mingw-win32/Release/CMakeFiles/CMakeOutput.log".
394See also "C:/projects/libiio/build-mingw-win32/Release/CMakeFiles/CMakeError.log".
395
```

**Comment by rgetz** [comment]
Do we use doxygen to create a microsoft help file? Otherwise - we could drop  doxygen for now.

**Comment by AlexandraTrifan** [comment]
The MSVC builds don't use it, so we could drop it for MinGW as well, until we figure out what went wrong with the new version.

**Comment by rgetz** [comment]
can we just downgrade to doxygen-1.8.14-2?

**Comment by rgetz** [comment]
Most recent fixes the appveyor build issues by fixing/downgrading the version of doxygen.

**Comment by AlexandraTrifan** [comment]
This looks good to me.

**Comment by rgetz** [comment]
I think this is OK to merge, and will fix the appveyour failures.

**Comment by commodo** [comment]
[LGTM](https://i.pinimg.com/564x/94/bc/8d/94bc8dc634e6a254794d3455daeb1c68.jpg)

**Pull request merged**
