### PR TITLE
CI: fix builds

### PR DESCRIPTION
**Pull request by ccraluca**
Fix Fedora-34 builds on Azure. In the 'Documentation' step, 'build' folder is removed so I swap the 'Documentation' and 'CopyFiles' steps.

Second commit: Linux repo have some links to libiio CI/travis folder. Temporary CI/travis folder will be added to fix Azure builds until finding a final solution.

Signed-off-by: Raluca Chis <raluca.chis@analog.com>

### CODE REVIEW

**Comment by pcercuei** [comment]
What's with the linux repo requiring the travis scripts in libiio? Could you give a bit more context?

**Comment by ccraluca** [comment]
I don't fully understand this process. Here(https://github.com/analogdevicesinc/linux/blob/master/ci/travis/lib.sh#:~:text=wget%20https%3A//raw.githubusercontent.com/analogdevicesinc/libiio/master/CI/travis/lib.sh%20%5C) you can see that in linux/ci/travis/lib.sh, there is a wget command with scripts in libiio.

**Comment by ccraluca** [comment]
That `wget` command takes only lib.sh script from libiio, but in Azure builds log(https://dev.azure.com/AnalogDevices/OpenSource/_build/results?buildId=10280&view=logs&j=879240bf-af41-502a-e8b7-76d2e609186a&t=46b80643-5435-52a4-ccad-03c9a4ab7e73#:~:text=https%3A//raw.githubusercontent.com/analogdevicesinc/libiio/master/CI/travis/inside_docker.sh) the somehow is used inside_doker.sh too.

**Comment by ccraluca** [comment]
You are right...I proposed that this be only temporary until I find a solution because now the builds on linux do not work at all and they need to run

**Comment by ccraluca** [comment]
Mention that those two files will not affect libiio CI or the previous updates

**Comment by pcercuei** [comment]
Hmmmmk. I'll merge it but I don't like it.

**Review by pcercuei — APPROVED** [review]

**Pull request merged**
