### PR TITLE
Rgetz move iio monitor

### PR DESCRIPTION
**Pull request by rgetz**
This moves iio-monitor to the test directory, (since it's built as a test file today) and gives it some help and common command line arguments.

### CODE REVIEW

**Comment by pcercuei** [comment]
Honestly, I'd just prevent it from being installed. The iio-monitor is a toy program which just acts as an example of how to use the API, so it does belong in "examples" IMHO.

**Comment by rgetz** [comment]
In the existing cmake - it gets installed in the debs - I can just remove it if that is the conclusion.

I use to show it to lots of people... (I always thought it was cool).

**Comment by pcercuei** [comment]
@rgetz it is cool but doesn't really provide any functionality unlike iio_attr / iio_info / iio_rwdev etc., it is more an experiment.

**Comment by rgetz** [comment]
Sure - I will nack this one then, and do something different than just unwinds the examples and tests.

**Pull request closed without merging**
