### PR TITLE
usb: add libusb version to context attributes

### PR DESCRIPTION
**Pull request by rgetz**
When debugging, it's always nice to know the libusb version. This makes it easy to find.

Signed-off-by: Robin Getz <robin.getz@analog.com>

### CODE REVIEW

**Comment by rgetz** [comment]
Looks like old/ancient versions of libusb don't support this, so I will need to ifdef this based on the libusb version. (It was added 2012-04-17: v1.0.10)

/libiio/usb.c: In function 'usb_populate_context_attrs':
/libiio/usb.c:743: warning: implicit declaration of function 'libusb_get_version'

So I will need to test with a #ifdef LIBUSB_API_VERSION (that was added Jan 8, 2014, replacing the older LIBUSBX_API_VERSION)
https://github.com/libusb/libusb/commit/1eff220474f63d7ea7f8f99bef2a3da9da5324eb
if we want to support the older distributions.

Thoughts?

**Comment by commodo** [comment]
I'd use the same mechanism that's around line 840:
```
#if defined(LIBUSB_API_VERSION) && (LIBUSB_API_VERSION >= 0x01000016)
    libusb_set_auto_detach_kernel_driver(hdl, true);
#endif
```

If we can find the libusb API version that introduced this, it would be neat, and a bit more robust.
Other than that, this looks good.

**Comment by pcercuei** [comment]
You could also check whether the function symbol exists, CMake supports that and IIRC we already do this for another function.

**Comment by rgetz** [comment]
LIBUSB_API_VERSION was added after libusb_get_version. If the define is there - the function exists. 

- Robin

**Comment by commodo** [comment]
Paul's suggestion also sounds nice.

**Comment by lclausen-adi** [comment]
Sounds nice, but is more work to get the same result.

**Comment by commodo** [comment]
Hmm, ok ; no strong opinion from me.
Let's have this as is.

If there aren't any strong opinions for other options, will merge this tomorrow

**Comment by rgetz** [comment]
Ok - I added @pcercuei  suggestion before I saw @lclausen-adi comment - let me know which version I should leave.

-Robin

**Comment by pcercuei** [comment]
Using LIBUSB_API_VERSION is fine with me.

**Comment by mhennerich** [comment]
Either way seems fine to me - let's merge this

**Comment by rgetz** [comment]
thanks

**Pull request merged**
