### PR TITLE
DNS SD implementation for macOS (Bonjour)

### PR DESCRIPTION
**Pull request by matejk**
Related to #307.

### CODE REVIEW

**Comment by rgetz** [comment]
This looks great to me - Just need to test things. Thanks for submitting.

**Comment by rgetz** [comment]
when running the small shell script
```while [ 1 ] ; do  x=0 ; i=0 ; while [ "${x}" -eq "0" ] ; do ./tests/iio_attr -d -u ip: >/dev/null ; x=$? ; i=$((i+1)) ; if [ "${x}" -eq "1" ] ; then echo "$i : ret= $x" ; fi; done; done```

I get:
```
Unable to create IIO context: Connection refused
120 : ret= 1
Unable to create IIO context: Connection refused
87 : ret= 1
Unable to create IIO context: Connection refused
1 : ret= 1
Unable to create IIO context: Invalid argument
1 : ret= 1
```

but it looks like that isn't new - so this works as well as it did before :)

If I look at the device it's attaching to, it's ZedBoard on my network, where I'm running iiod.
```
root@analog:~# ip  addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0a:35:00:01:22 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.120/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
```

If I print out the address/port that it finds, it normally files the ZedBoard.

Sometimes it finds an IPv6 number.and I think we are passing that to the IPv4 framework..

```
found : fe80::689c:66a7:fbaa:ce88:30431
Unable to create IIO context: Invalid argument
94 : ret= 1
```

The weird part is that is my host PC with a Pluto attached.
```
rgetz@brain:~/github/temp/libiio/build$ ip -6 addr
4: enx00e0229bee20: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UNKNOWN qlen 1000
    inet6 fe80::689c:66a7:fbaa:ce88/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

and

```
found : 192.168.2.10:30431
Unable to create IIO context: Connection refused
32 : ret= 1
```

`192.168.2.10` is the PC that I'm running on (again - the local IP of the PlutoSDR connected USB)
```
rgetz@brain:~/github/temp/libiio/build$ ip addr show dev enx00e0229bee20
4: enx00e0229bee20: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 00:e0:22:9b:ee:20 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.10/24 brd 192.168.2.255 scope global dynamic noprefixroute enx00e0229bee20
       valid_lft 813811sec preferred_lft 813811sec
    inet6 fe80::689c:66a7:fbaa:ce88/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```
so that is weird/wrong. It should respond on 192.168.2.1, but not 10.

Again - I think these both exist on master as well, I just don't know if we wanted to fix them as part of this or not...

**Comment by matejk** [comment]
@rgetz : Did you run the script on Linux (Avahi) or macOS (Bonjour)?

Implementation for macOS prefers ipv4 address over ipv6 if the OS gives both.

**Comment by rgetz** [comment]
This was on Linux.I don't know if @tfcollins can test on macOS with a similar setup (something on LAN that would respond as well as Pluto plugged in).

**Comment by matejk** [comment]
Implementation in this PR implements same behaviour as it is there for Avahi already.

Current implementation of DNS SD (either Avahi or Bonjour) in libiio is intended only for network environments with only one IIOD. To support multiple IIOD servers it would have to be implemented differently. But that it is out of scope of this PR.

**Comment by rgetz** [comment]
Agreed. I can replicate the behavior described on old releases as well.

Sometimes - it would respond with the IP address of the machine it was running on, so there is something weird going on. I will open a separate issue, and wait for @tfcollins to confirm operation on macOS.

That only leaves Win32 as something that isn't supported... Now that we have a Bonjour implementation (thanks again) - it should be straightforward to do something eventually. (not in this PR, as I think it would be much more complicated - you would want to dlopen() the library yourself, since it's not always on Windows, and I don't think you want to force people to install it - its part of iTunes, or Apple Print Services https://support.apple.com/kb/DL999?viewlocale=en_US&locale=en_US ).

**Comment by matejk** [comment]
Perhaps it is better to use MS implementation for DNS SD as described here:

https://docs.microsoft.com/en-us/uwp/api/windows.networking.servicediscovery.dnssd

I am not sure for which Windows versions is this available, but it is on Windows 10 almost definitely.

**Comment by rgetz** [comment]
Thanks for pointer - I will have a look at those.

**Pull request merged**
