### PR TITLE
[libiio-v0] Add CODEOWNERS and PULL_REQUEST_TEMPLATE files

### PR DESCRIPTION
**Pull request by SRaus**
## PR Description

--cherry picked from commit https://github.com/analogdevicesinc/libiio/commit/b4c951101f2867a9f97e291e91b904a2a705dfe7 to libiio-v0 branch.

Persons specified in CODEOWNERS file will be automatically added as reviewers, whenever new PRs are opened, depending on affected folder. In addition to Code Owners, other reviewers can be added to each PR. CODEOWNERS file can be different from one branch to another. All new PRs will require the approval of at least one code owner.

PULL_REQUEST_TEMPLATE.md will populate all new PR description field. Beside PR description, it contains a list of checkboxes, ensuring everyone follows the same guidelines and enforces best practices. Pull Request Template applies for PRs against all protected branches.

Both files got added in .github

Signed-off-by: Stefan Raus <Stefan.Raus@analog.com>

## PR Type
- [ ] Bug fix (a change that fixes an issue)
- [x] New feature (a change that adds new functionality)
- [ ] Breaking change (a change that affects other repos or cause CIs to fail)

## PR Checklist
- [x] I have conducted a self-review of my own code changes
- [x] I have commented new code, particularly complex or unclear areas
- [x] I have checked that I did not introduced new warnings or errors (CI output)
- [x] I have checked that components that use libiio did not get broken
- [x] I have updated the documentation accordingly (GitHub Pages, READMEs, etc)

### CODE REVIEW

**Comment by SRaus** [comment]
> I don't see the point of adding this to the v0 maintenance branch, as it doesn't fix anything, and thus violates the "only fixes" into this branch.

Maybe PR Template won't make sense, but we add CODEOWNERS to have more control of pushed PRs/changes. Code Owners are added automatically added as reviewers, whenever new PRs are opened and all PRs will require the approval of at least one code owner. The plan is to have these files in all branches that we want to keep more stable -  main, v0, release branches and so on.

**Comment by rgetz** [comment]
This creates noise on a stable "only fixes" branch that people upstream look at.

Please do not do it.

**Review by rgetz — CHANGES_REQUESTED** [review]
This is not necessary in the historic v0 release branch.

The project README.md states: 
```
Libiio v0.x is now considered legacy, and as such, only important bug fixes will be accepted into this branch.
```

This is is not important, and is not a bug fix.

**Comment by nunojsa** [comment]
> This is is not important, and is not a bug fix.

Agreed... @SRaus I guess you can close this PR

**Pull request closed without merging**
