### PR TITLE
packaging: update

### PR DESCRIPTION
**Pull request by rgetz**
when things moved from travis-ci to azure, some packaging options were lost. Specifically DEB_DETECT_DEPENDENCIES for debian based systems. This ensures that the version numbers from the host systems are put in the deb files so that things are actually compaitible with the downstream systems.

Turn that back on, and fix the issues that weren't seen over the last 3 years while this was turned off.

### CODE REVIEW

**Comment by rgetz** [comment]
First - don't we want to turn on hwmon and serial in all? the ones built from `CI/azure/ci-ubuntu.sh` have `-DWITH_HWMON=ON -DWITH_SERIAL_BACKEND=ON`, but that is missing from `azure-pipelines.yml`

from CI:

LinuxBuilds ubuntu_22_04
```
-- querying installed packages on system for dependancies
-- Package dependencies (.deb): libc6 (>= 2.35), libaio1 (>= 0.3.112), libavahi-client3 (>= 0.8), libavahi-common3 (>= 0.8), libusb-1.0-0 (>= 2:1.0.25), libxml2 (>= 2.9.13)
-- Features enabled : xml network dns-sd avahi ipv6 local local-mmap usb utils iiod udev-rule iiod-serial iiod-aio iiod-usb doc man man-utils python-bindings
-- Features disabled: zstd bonjour serial hwmon examples iiod-systemd iiod-sysvinit iiod-upstart c#-bindings
```

LinuxBuilds ubuntu_20_04
```
-- querying installed packages on system for dependancies
-- Package dependencies (.deb): libc6 (>= 2.31), libaio1 (>= 0.3.112), libavahi-client3 (>= 0.7), libavahi-common3 (>= 0.7), libusb-1.0-0 (>= 2:1.0.23), libxml2 (>= 2.9.10)
-- Features enabled : xml network dns-sd avahi ipv6 local local-mmap usb utils iiod udev-rule iiod-serial iiod-aio iiod-usb doc man man-utils python-bindings
-- Features disabled: zstd bonjour serial hwmon examples iiod-systemd iiod-sysvinit iiod-upstart c#-bindings
```
don't we want to turn on hwmon and serial?

LinuxBuilds fedora34
```
-- Using default dependencies for packaging, try turning on -DDEB_DETECT_DEPENDENCIES=ON
-- Package dependencies (.deb): libc6 (>= 2.19), libaio1 (>= 0.3.109), libavahi-client3 (>= 0.6.31), libavahi-common3 (>= 0.6.31), libusb-1.0-0 (>= 2:1.0.17), libxml2 (>= 2.9.1)
-- Package dependencies (.rpm): libaio >= 0.3.107, avahi >= 0.6.25, libusb1 >= 1.0.9, libxml2 >= 2.7.6
-- Features enabled : xml network dns-sd avahi ipv6 local local-mmap usb utils iiod udev-rule iiod-serial iiod-aio iiod-usb doc man man-utils python-bindings
-- Features disabled: zstd bonjour serial hwmon examples iiod-systemd iiod-sysvinit iiod-upstart c#-bindings
```

ARMBuilds ubuntu-ppc64le
```
-- querying installed packages on system for dependancies
-- Package dependencies (.deb): libc6 (>= 2.31), libaio1 (>= 0.3.112), libavahi-client3 (>= 0.7), libavahi-common3 (>= 0.7), libusb-1.0-0 (>= 2:1.0.23), libxml2 (>= 2.9.10), libserialport0 (>= 0.1.1)
-- Features enabled : xml network dns-sd avahi ipv6 serial local local-mmap hwmon usb utils examples iiod udev-rule iiod-serial iiod-aio iiod-usb man-utils python-bindings
-- Features disabled: zstd bonjour iiod-systemd iiod-sysvinit iiod-upstart doc man c#-bindings
```

ARMBuilds ubuntu-x390x
```
-- querying installed packages on system for dependancies
-- Package dependencies (.deb): libc6 (>= 2.31), libaio1 (>= 0.3.112), libavahi-client3 (>= 0.7), libavahi-common3 (>= 0.7), libusb-1.0-0 (>= 2:1.0.23), libxml2 (>= 2.9.10), libserialport0 (>= 0.1.1)
-- Features enabled : xml network dns-sd avahi ipv6 serial local local-mmap hwmon usb utils examples iiod udev-rule iiod-serial iiod-aio iiod-usb man-utils python-bindings
-- Features disabled: zstd bonjour iiod-systemd iiod-sysvinit iiod-upstart doc man c#-bindings
```

ARMBuilds ubuntu-arm64v8
```
-- querying installed packages on system for dependancies
-- Package dependencies (.deb): libc6 (>= 2.31), libaio1 (>= 0.3.112), libavahi-client3 (>= 0.7), libavahi-common3 (>= 0.7), libusb-1.0-0 (>= 2:1.0.23), libxml2 (>= 2.9.10), libserialport0 (>= 0.1.1)
-- Features enabled : xml network dns-sd avahi ipv6 serial local local-mmap hwmon usb utils examples iiod udev-rule iiod-serial iiod-aio iiod-usb man-utils python-bindings
-- Features disabled: zstd bonjour iiod-systemd iiod-sysvinit iiod-upstart doc man c#-bindings
```

ARMBuilds ubuntu-arm32v7
```
-- querying installed packages on system for dependancies
-- Package dependencies (.deb): libc6 (>= 2.31), libaio1 (>= 0.3.112), libavahi-client3 (>= 0.7), libavahi-common3 (>= 0.7), libusb-1.0-0 (>= 2:1.0.23), libxml2 (>= 2.9.10), libserialport0 (>= 0.1.1)
-- Features enabled : xml network dns-sd avahi ipv6 serial local local-mmap hwmon usb utils examples iiod udev-rule iiod-serial iiod-aio iiod-usb man-utils python-bindings
-- Features disabled: zstd bonjour iiod-systemd iiod-sysvinit iiod-upstart doc man c#-bindings
```

So, I need to get the rpm and zypper autodetecting as well (after #969 is merged)

**Comment by pcercuei** [comment]
I believe it makes sense to enable hwmon and serial, yes.

**Comment by rgetz** [comment]
Will do.

**Comment by rgetz** [comment]
Just so I can keep track of things:
```
ubuntu_18_04    | libc6 (>= 2.27), libaio1 (>= 0.3.110), libavahi-client3 (>= 0.7), libavahi-common3 (>= 0.7), libusb-1.0-0 (>= 2:1.0.21), libxml2 (>= 2.9.4), libserialport0 (>= 0.1.1)
ubuntu_20_04    | libc6 (>= 2.31), libaio1 (>= 0.3.112), libavahi-client3 (>= 0.7), libavahi-common3 (>= 0.7), libusb-1.0-0 (>= 2:1.0.23), libxml2 (>= 2.9.10), libserialport0 (>= 0.1.1)
debian_bullseye | libc6 (>= 2.31), libaio1 (>= 0.3.112), libavahi-client3 (>= 0.8), libavahi-common3 (>= 0.8), libusb-1.0-0 (>= 2:1.0.24), libxml2 (>= 2.9.10), libserialport0 (>= 0.1.1)
ubuntu-ppc64le  | libc6 (>= 2.31), libaio1 (>= 0.3.112), libavahi-client3 (>= 0.7), libavahi-common3 (>= 0.7), libusb-1.0-0 (>= 2:1.0.23), libxml2 (>= 2.9.10), libserialport0 (>= 0.1.1)
ubuntu-x390x    | libc6 (>= 2.31), libaio1 (>= 0.3.112), libavahi-client3 (>= 0.7), libavahi-common3 (>= 0.7), libusb-1.0-0 (>= 2:1.0.23), libxml2 (>= 2.9.10), libserialport0 (>= 0.1.1)
ubuntu-arm64v8  | libc6 (>= 2.31), libaio1 (>= 0.3.112), libavahi-client3 (>= 0.7), libavahi-common3 (>= 0.7), libusb-1.0-0 (>= 2:1.0.23), libxml2 (>= 2.9.10), libserialport0 (>= 0.1.1)
ubuntu-arm32v7  | libc6 (>= 2.31), libaio1 (>= 0.3.112), libavahi-client3 (>= 0.7), libavahi-common3 (>= 0.7), libusb-1.0-0 (>= 2:1.0.23), libxml2 (>= 2.9.10), libserialport0 (>= 0.1.1)
ubuntu_22_04    | libc6 (>= 2.35), libaio1 (>= 0.3.112), libavahi-client3 (>= 0.8), libavahi-common3 (>= 0.8), libusb-1.0-0 (>= 2:1.0.25), libxml2 (>= 2.9.13), libserialport0 (>= 0.1.1)

CentOS 7      | glibc >= 2.17, libaio >= 0.3.109, avahi >= 0.6.31, avahi-libs >= 0.6.31, libxml2 >= 2.9.1
fedora28      | glibc >= 2.27, libaio >= 0.3.110, avahi >= 0.7, avahi-libs >= 0.7, libusb >= 0.1.5, libxml2 >= 2.9.8, libserialport >= 0.1.1
opensuse_15_4 | glibc >= 2.31, libaio1 >= 0.3.109, avahi >= 0.8, libusb-1_0-0 >= 1.0.24, libxml2-2 >= 2.9.14, libserialport0 >= 0.1.1
fedora34      | glibc >= 2.33, libaio >= 0.3.111, avahi-libs >= 0.8, avahi >= 0.8, libusb >= 0.1.7, libxml2 >= 2.9.13, libserialport >= 0.1.1

```

**Review by nunojsa — APPROVED** [review]
LGTM to the best of my knowledge (not that familiar with deb and rpm packaging...) One question though... I got the impression we wanted to enable hwmon and serial for CI? is that being done?

**Comment by rgetz** [comment]
That was done separately as #977 since it wasn't really part of this (and is already merged).

**Comment by pcercuei** [comment]
@rgetz LGTM, is it ready for merge now?

**Comment by rgetz** [comment]
Will fix the spelling errors the check pointed out - it sucks that this check need to be done by hand.

```
Error: ./cmake/add_requirements2tar.sh.in:28: appart ==> apart
Error: ./cmake/LinuxPackaging.cmake:47: dependancies ==> dependencies
Error: ./cmake/LinuxPackaging.cmake:72: dependancies ==> dependencies
Error: ./cmake/LinuxPackaging.cmake:86: dependancy ==> dependency
Error: ./cmake/LinuxPackaging.cmake:151: seperated ==> separated
Error: ./cmake/LinuxPackaging.cmake:203: dependancy ==> dependency
```

**Pull request merged**
