### PR TITLE
Rgetz iiod enable ip numbers

### PR DESCRIPTION
**Pull request by rgetz**
print out IP numbers when clients connect.

### CODE REVIEW

**Comment by tfcollins** [comment]
I'm wondering the downside here. So if we run the stress test will the log explode?

**Comment by pcercuei** [comment]
@tfcollins it shouldn't, the amount of data printed varies very little.

**Comment by rgetz** [comment]
>So if we run the stress test will the log explode?

The "add" is to replace `0.0.0.0` with the actual/proper IP number: `192.168.122.1` or `fe80::fc54:ff:fe57:b2c7%vnet5` so I think the log will fill up no matter what .... :)

-Robin

**Comment by pcercuei** [comment]
No idea why Codacy still complains. It looks OK to me now.

**Review by pcercuei — APPROVED** [review]

**Pull request merged**
