### PR TITLE
iiod/init: add a script which creates /etc/libiio.ini and bolt it in

### PR DESCRIPTION
**Pull request by rgetz**
This add a small script /usr/sbin/iiod_create_ini which can create a
/etc/libiio.ini file. This is connected to the startup scripts, and run
before iiod, so that things are populated on time.

Re-work a little of the CMake so that this is included during an
install.

Update the doc (the README_BUILD.md) so these options are clear for
people.

This is the first stage of #593

Signed-off-by: Robin Getz <robin.getz@analog.com>

### CODE REVIEW

**Review by tfcollins — COMMENTED** [review]
Have we been able to test all 3?

**Comment by rgetz** [comment]
I have tested the ini creation on x86, Zynq and Pi.
I have tested the sysvinit (Zynq) and systemd (x86 & Pi).

Upstart didn't change much from the existing code.

**Comment by mhennerich** [comment]
https://github.com/analogdevicesinc/linux_image_ADI-scripts/blob/master/iiod_usbd.init#L84

We also handle UDC (usb_gadget) and IIO USB functionfs support.
Do we want that to include here as well? It matters since IIOD needs to be started differently.

**Comment by rgetz** [comment]
Can do - that makes sense.

I would have a uniq script to set up the gadget device (which is common, and will be less copy/paste across the different init systems). basically what is in here: https://github.com/analogdevicesinc/linux_image_ADI-scripts/blob/master/iiod_usbd.init#L84-L112

**Comment by mirceacaprioru** [comment]
I was working on some systemd services for UDC. Systemd has the possibility to trigger services based on folder updates like the /sys/class/udc.

 I have not succeeded  in testing this services using the ZCU102. But if we add them to libiio that would be great from my side too since they are tied.

**Comment by rgetz** [comment]
> But if we add them to libiio that would be great from my side too since they are tied.

What specifically do you need?

**Comment by mirceacaprioru** [comment]
It is basically just splitting this script that you also pointed out before: https://github.com/analogdevicesinc/linux_image_ADI-scripts/blob/master/iiod_usbd.init#L84-L130

**Comment by rgetz** [comment]
I have something that I think works - but I need to test a lot more on a few different systems before it's merged.

**Comment by rgetz** [comment]
getting back to this - has anyone else tested this but me? I will update to latest master if no one has any comments.

**Comment by mhennerich** [comment]
Please see here: 

https://github.com/analogdevicesinc/linux_image_ADI-scripts/pull/27

This does effectively the same and can live completely outside libiio

**Comment by rgetz** [comment]
I think this was replaced with https://github.com/analogdevicesinc/linux_image_ADI-scripts/pull/27

**Pull request closed without merging**
