### PR TITLE
Fixed declaration of 'buf' hides previous local declaration

### PR DESCRIPTION
**Pull request by f4exb**

### CODE REVIEW

**Comment by dNechita** [comment]
Can you please sign-off your commit? Thanks!

**Comment by f4exb** [comment]
What do you mean by "sign off" ?

**Comment by dNechita** [comment]
It just a matter of recreating the commit but this time append option '-s' when you create the commit.
The meaning of signing commits cat be found at:
https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Comment by rgetz** [comment]
thanks for the fix.

**Review by dNechita — APPROVED** [review]

**Pull request merged**
