### PR TITLE
Support Android builds

### PR DESCRIPTION
**Pull request by gburca**
Added `Android.mk` file so that libiio can be built on Android.

### CODE REVIEW

**Comment by pcercuei** [comment]
Pretty cool, thanks!

Two things:
* Could you add your signed-off-by line?
* Android.mk:26 refers to an "external" directory, is that supposed to be present in the source tree?

Thanks,
-Paul

**Comment by gburca** [comment]
`external/libxml2` is part of AOSP, however I haven't tested the network backend, so that's why it's not compiled in by default.

I don't think the signed-off-by line can be added without rewriting the git history. How does github handle merge requests whose SHA1 suddenly disappears?

**Comment by lclausen-adi** [comment]
Just send a new pull-request with the signed-off added.

**Comment by rgetz** [comment]
Does this want to get merged in before 0.9? I think I can use travis to build test things going forward.

**Comment by pcercuei** [comment]
So I had comments on the commits that got dropped when the branch was force-pushed.
Mainly it was for the documentation tweaks to be done in a separate commit since they are unrelated.

This PR was done in March 2016, it's safe to assume that it won't work anymore with the current libiio master, so no need to rush it for the 0.9 release.

**Comment by adisuciu** [comment]
https://github.com/analogdevicesinc/libiio/pull/728 adds support for Android using NDK and CMake https://developer.android.com/ndk/guides/cmake. 

This PR proposes another build method for Android, indepenedent from CMake. It's better if we stick to a single build method for all platforms.

I think we can close this.

**Comment by pcercuei** [comment]
Closing then.

**Pull request closed without merging**
