### PR TITLE
python binding improvements

### PR DESCRIPTION
**Pull request by rgetz**
This will add some python code formatting detaults (black) and fix some issues pointed out by the pylint file.

### CODE REVIEW

**Comment by rgetz** [comment]
After a quick discussion with @cristi-iacob ; we came to conclusion I would work on iio.py and formatters in this pull request, and he would work on the examples in a separate one, since I think he is re-writing most of the examples so they are more python friendly, and not a python implementation of the C code...

**Comment by rgetz** [comment]
This updates iio.py from:
image

to:
image

I opened a few issues for others to have a look at:
 - #

**Comment by rgetz** [comment]
This does still have a few issues - but I think is ready to go (with Travis's help).
image

**Comment by rgetz** [comment]
everything is building the communication between github <-> Travis-CI is broken.

**Comment by tfcollins** [comment]
Changes have been validated against hardware CI

**Pull request merged**
