### PR TITLE
Python: More robust loading of IIO library

### PR DESCRIPTION
**Pull request by matejk**
Python: More robust loading of IIO library that works on different platforms.

This improvement is based on work of Emmanuel Blot (eblot).

Tested-by: Matej Kenda <matejken@gmail.com>

### CODE REVIEW

**Comment by rgetz** [comment]
Thanks for pushing upstream.

I think we need a signed-off-by @eblot before we can commit. (if you only tested it?)

**Comment by eblot** [comment]
I can do that if you want me to, but I do not know how to sign at this stage. Any pointer to how to proceed would be warmly welcomed. Thanks.

**Comment by mhennerich** [comment]
If you would have crated the PR - it would be as simple as amend commit and push.
The PR would update. 
Maybe you update your branch - and @matejk merges it?

**Comment by matejk** [comment]
Would it work if I amend the commit and push it if @eblot agrees?

**Comment by mhennerich** [comment]
I think so

**Comment by eblot** [comment]
I do agree, it is really such a small patch... the simpler the better.

**Comment by matejk** [comment]
Agreed changes of signed-off a few months ago. I hope it is OK to merge.

**Comment by mhennerich** [comment]
looks good to me now - but adding some more reviewers.

**Comment by commodo** [comment]
the code looks ok;
the commits look a bit weird;
i see 3 commits for the same change [1 merge commit + 2 other]

it would be nice to have a single one, but fine to leave it as-is, if the intent is to preserve hashes

**Comment by mhennerich** [comment]
merged

**Pull request merged**
