### PR TITLE
sort the channels array on device or trigger init

### PR DESCRIPTION
**Pull request by beOn**
related to https://ez.analog.com/message/209741#209741

Signed-off-by: Ben Acland <benacland@gmail.com>

### CODE REVIEW

**Comment by pcercuei** [comment]
Could you add a Signed-Off-By line?
Then I will merge it.

Thanks!

**Comment by beOn** [comment]
Updated

**Comment by pcercuei** [comment]
Could you put the Signed-Off-By line in the commit message instead? :)

**Comment by beOn** [comment]
Sometimes it's fun just to sign off whatever.

Fixed.

**Pull request merged**
