### PR TITLE
Revert ".travis.yml: move SSH key logic into shell script from yaml file

### PR DESCRIPTION
**Pull request by commodo**
These patches sexpose a security risk, by potentially displaying secret
information in the logs.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>

### CODE REVIEW

**Comment by commodo** [comment]
Is there another commit I should revert ?

Maybe this ?
https://github.com/analogdevicesinc/libiio/commit/3724ea604a7d584a2c6ab1381d2a81a420989f17

**Comment by pcercuei** [comment]
Add a bit of context in the commit message maybe? I have no clue why this gets reverted.

**Comment by rgetz** [comment]
Moving these from the yaml, and assigning them to other shell variables - last time I did this in travis-ci - exposes them sometimes to the travis-ci log in plain text, and allows everyone in the world to read them (which is sort of the opposite of what you want to do with your secret ssh key, or anything that could be used as an attack surface in travis-ci).

I don't think Alex was familiar with these issues - but the changes were proposed, and committed over thanksgiving (in the US) when I was enjoying a day off - and was merged to master without my review (not that I should review every commit, but I have been working on the build system/travis-ci for a long time) and I need to spend some time going through all the Travis-ci logs on Monday to see what keys need to be revoked, and what code needs to be changed back. (while I understand the desire for build system beautification - it was working fine, I'm not sure I understand the motivation to change everything - but that is a different question).

**Comment by commodo** [comment]
I'll add a short comment to the commits & PR.

Regarding the beautification, that was more of an intermediate step towards getting here https://github.com/analogdevicesinc/libiio/pull/231 , which is having a common code that can be used to start a pipeline, where libiio `<triggers>` libad9361-iio `<triggers>` iio-osciloscope & gr-iio `<triggers>` scopy. The intent is that if something changes deployment-wise, we update a single point (which for the moment is libiio) and all deployments should synchronize by using the deployment code.
I will admit I got (and still usually get) carried away by over-doing things sometimes.

**Comment by commodo** [comment]
If no other objections, will merge this tomorrow.

**Pull request merged**
