### PR TITLE
Fix data convert function in python bindings

### PR DESCRIPTION
**Pull request by tfcollins**
The python binding to convert did not work at all. This updates the convert function and was tested
with devices with various buffer datatypes.

Signed-off-by: Travis F. Collins <travis.collins@analog.com>

### CODE REVIEW

**Comment by tfcollins** [comment]
I can add my tests just need a couple days

**Comment by pcercuei** [comment]
@tfcollins The convert function works as intended... it just doesn't perform what you expect it to do. Have a look at Channel.read() instead.

**Comment by tfcollins** [comment]
@pcercuei The c function of convert operates on single samples. Are you expecting the python convert function to take a list of length 1? How is the python binding supposed to work?

**Comment by pcercuei** [comment]
Yes, basically buffer.read() gives you a byte array, and you can convert individual values using channel.convert().

**Comment by tfcollins** [comment]
That doesn't really make any sense base on the current method. If I pass a list as documented `(c_char * (len(dst) * self.data_format.length))(*dst)` will create a new object which I do not have access to. Then _convert will update that object and not a reference to the thing I passed.

**Comment by pcercuei** [comment]
I was trying to remember how that function is supposed to be used, but it turns out it's not my code. Maybe @cristi-iacob can help?

**Comment by tfcollins** [comment]
So if you want it to map more to the C API, I would argue we just return the pointer and not rely on pass-by object. I can put the looping logic and pointer math into a pyadi-iio method. Kinda like gr-iio.

-Travis

**Comment by pcercuei** [comment]
@tfcollins what annoys me with your solution is that it's basically a duplicate of Channel.read().

I don't know why Channel.convert() was added, or if it's used anywhere, but we can't just rewrite it to make it functionally different, without breaking the API...

**Pull request closed without merging**
