### PR TITLE
CI:update ci

### PR DESCRIPTION
**Pull request by ccraluca**
Remove deprecated os versions from Azure builds.

Signed-off-by: Raluca Chis <raluca.chis@analog.com>

### CODE REVIEW

**Comment by pcercuei** [comment]
That's fine with me, but I didn't know we were stopping supporting Ubuntu 18.04?

**Comment by ccraluca** [comment]
Ubuntu 18.04 is deprecated starting 8/8/2022 and unsupported by 12/2/2022. We can continue for a few more months until will be unsupported by Azure Pipelines.
macOS X Catalina 10.15 will be unsupported by 9/30/2022.

**Comment by ccraluca** [comment]
Sure, no problem. It is ok if I convert it to a draft until will be the case to be removed?

**Comment by pcercuei** [comment]
@ccraluca Fine with me, but please change the base branch to the "dev" one instead of "master" then.

**Comment by ccraluca** [comment]
V2: remove only Catalina

**Review by pcercuei — APPROVED** [review]

**Pull request merged**
