### PR TITLE
Switch libiio CI config to more standard yaml

### PR DESCRIPTION
**Pull request by ccraluca**
1. CI: switch libiio CI config to more standard yaml
  - eliminate scripts and use code directly in azure-pipelines.yml
  - modify builds to use docker images containing all dependencies in order to reduce build time
  - modify files related to artifacts according to new builds

2. CI: add artifact_manifest file
  - the purpose of this file is to have on GitHub repository a list with all deployed artifacts
  - this list will be checked in Azure Pipelines at each master push

3. CI: update CI folder structure
  - remove unused files
  - move used files to 'azure' folder
  - update paths to moved files

### CODE REVIEW

**Comment by pcercuei** [comment]
@ccraluca I merged @rgetz's pull request first, your PR now has conflicts. Sorry about that.
The CI also complains a bit about the new code, but it all seems very easy to fix, could you maybe try to fix them before we merge this? Thanks!

**Comment by rgetz** [comment]
Most likely want to fix the codacity issues as well.

**Comment by ccraluca** [comment]
Conflicts resolved and codacity issues fixed.

**Review by pcercuei — APPROVED** [review]
But I like the diff!

**Comment by ccraluca** [comment]
I forgot to mention, after the first run on the master there will be a PR containing updates for the files resulting in SWDownloads and README.md file which cannot be done only after running in the master

**Pull request merged**
