### PR TITLE
iiod: support compiling without v0.x compatibility

### PR DESCRIPTION
**Pull request by pcercuei**
Add support for compiling only with the binary interface, stripping away the ASCII protocol implemented in ops.c, and the flex/bison interpreter.

### CODE REVIEW

**Review by buha — APPROVED** [review]

**Review by mhennerich — APPROVED** [review]

**Comment by rgetz** [comment]
Need to add/document `WITH_IIOD_V0_COMPAT` to the `README_BUILD.md` that will fix the failing CI (other than Codacy issues)

**Comment by rgetz** [comment]
do you still need to compile iiod/ops.c if ASCII is turned off?

**Comment by pcercuei** [comment]
> do you still need to compile iiod/ops.c if ASCII is turned off?

No

**Comment by rgetz** [comment]
> No

Sorry - I missed it was protected inside the if/endif on first glance...

Other than the missing doc - looks good to me.

**Pull request merged**
