### PR TITLE
Polishing for C++

### PR DESCRIPTION
**Pull request by sternmull**
This adds some minor improvements that came up after the previous pull request was accepted.

### CODE REVIEW

**Comment by rgetz** [comment]
I also noticed that the CPP does't print out in the CMAKE at the end.

It just needs a simple `toggle_iio_feature("${CPP_BINDINGS}" "c++-headers")` or something similar. (although I guess we don't do it for the other bindings either - but maybe that's a good idea too?)

**Comment by pcercuei** [comment]
Please remember to sign your commits, we cannot merge them otherwise.

**Comment by sternmull** [comment]
> Please remember to sign your commits, we cannot merge them otherwise.

Done. Pushed the updated commits.

**Comment by sternmull** [comment]
@julienmalik Thank you! Not to late for this pull request. Added a commit that fixes it.

**Comment by pcercuei** [comment]
@sternmull could you add a call to `toggle_iio_feature()` in bindings/CMakeLists.txt, the same way it's done for Python and C#?

**Comment by sternmull** [comment]
@pcercuei Done.

**Review by pcercuei — APPROVED** [review]

**Pull request merged**
