### PR TITLE
Add support for hardware-monitoring devices

### PR DESCRIPTION
**Pull request by pcercuei**
This PR adds support for hardware monitoring (hwmon) devices. The hwmon devices can now be used as regular iio_device and iio_channel objects.

This option is guarded behind a `WITH_HWMON` CMake option, disabled by default. The reason behind this choice is that some applications might use the local backend failing to instanciate as a pointer that there are no IIO devices.

@rgetz I added your signed-off-by and co-developed-by, but since you wrote most of these changes, I can make you the author and put myself as the co-developer.

### CODE REVIEW

**Comment by pcercuei** [comment]
The reports from Codacity can be ignored.

**Comment by nunojsa** [comment]
Are we trying to re-implement libsensors? I can imagine why it is tempting to support this through libiio and make use of it's backends channels but to me, this can be opening a "dangerous" door. I guess if we do not start now supporting all kind of devices through libiio, this is fine as hwmon and iio devices are sometimes very similar and overlapping. I would still make it clear they are different things like having a different public header for hwmon devices or maybe just have some hwmo_to_iio bridge code as in the kernel...

Just my 2 cents.

**Comment by pcercuei** [comment]
@nunojsa hwmon are basically IIO devices that somebody decided to use as "hardware monitoring". Ideally hwmon should be phased out completely, and replaced with IIO drivers with a "iio to hwmon" bridge (which already exists).

I'd be against supporting something completely unrelated in libiio (e.g. some kind of GPIO control library), but hwmon being just a dumbed-down IIO, the diff is actually extremely small. That makes it okay for me.

**Comment by nunojsa** [comment]
Well, they have more stuff like FAN controllers and things like that. The ABI is also fairly different. But yeah, what you stated is fair (hwmon is acceptable but more than that is probably crossing the line already). They are quite similar and there are lot's of overlaps sometimes (eg: temperature sensors).

**Comment by pcercuei** [comment]
The ABI is actually very similar, you have one top folder containing <dev_id> folders, in which you have <chan_id>_<attribute> files. There are a few difference (e.g. modifiers) but overall it's more of the same.

**Comment by mthoren-adi** [comment]
@pcercuei I am up and running with the PowerStick, an LM75 (generic, not ADI's ADT75) and an ADT7420. After a cursory look, it seems like the power system management devices show up fine (LTC2974, LTC2978, LTC3880).

The LM75 shows up running iio_info on the local backend, but the ADT7420 is lost - I think it corresponds to hwmon5 (see iio_info_output_expermenter_rpi_local.txt)

Neither the LM75 nor ADT7420 show up through the network backend (iio_info -u ip:localhost) , see iio_info_output_expermenter_rpi_local.txt. (Same behavior when I run iio_info -u experimenter.local from my Windows laptop.)

I did reboot after installing to make sure the new iiod was running.

For comparison, sensors_output_expermenter_rpi.txt is the output of the sensors lm-sensors utility.

Any other tests come to mind? I'll see if I can find any other HWMON parts lying around, I may have an LTC2945.

[iio_info_output_expermenter_rpi_ip_localhost.txt](https://github.com/analogdevicesinc/libiio/files/7652528/iio_info_output_expermenter_rpi_ip_localhost.txt)
[sensors_output_expermenter_rpi.txt](https://github.com/analogdevicesinc/libiio/files/7652529/sensors_output_expermenter_rpi.txt)
[iio_info_output_expermenter_rpi_local.txt](https://github.com/analogdevicesinc/libiio/files/7652531/iio_info_output_expermenter_rpi_local.txt)

**Comment by pcercuei** [comment]
@mthoren-adi Could you run:
```
sudo find /sys/class/hwmon/hwmon5/
```
And repeat the operation for any other hwmonX which you think is not correct.

**Comment by mthoren-adi** [comment]
> @mthoren-adi Could you run:
> 
> ```
> sudo find /sys/class/hwmon/hwmon5/
> ```
> 
> And repeat the operation for any other hwmonX which you think is not correct.


@pcercuei see attached. I went a layer deeper on the last 3 devices (LTC3880, ADT7420, LM75).

-Mark

[experimenter_hwmon_sys_files.txt](https://github.com/analogdevicesinc/libiio/files/7656214/experimenter_hwmon_sys_files.txt)

**Comment by rgetz** [comment]
>@rgetz I added your signed-off-by and co-developed-by, but since you wrote most of these changes, I can make you the author and put myself as the co-developer.

What you have is fine - thanks for doing this.

**Comment by rgetz** [comment]
I think @mthoren-adi was running into this issue: https://github.com/analogdevicesinc/linux/pull/1647/ We just need to wait for that to be merged.

**Comment by rgetz** [comment]
couple comments:
- missing the `WITH_HWMON` in `README_BUILD.md`
- missing in the feature summary:
```
-- Features enabled : xml network dns-sd avahi ipv6 local usb utils iiod iiod-serial iiod-aio iiod-usb man-utils
-- Features disabled: zstd serial examples iiod-systemd iiod-sysvinit iiod-upstart doc man python-bindings c#-bindings
```

otherwise - looks fine to me.

**Comment by pcercuei** [comment]
@rgetz done.

**Review by rgetz — APPROVED** [review]

**Comment by rgetz** [comment]
Thanks - looks good to me.

**Comment by nunojsa** [comment]
> I think @mthoren-adi was running into this issue: analogdevicesinc/linux#1647 We just need to wait for that to be merged.

Just a comment here... As noted in that PR, that is not really an issue. It's just the legacy path where to find HWMON devices. So we can very well update that driver to the new ABI but that does not mean that libiio will fail with some other devices using the legacy path (drivers that we might not control). libsensors apparently handles both paths so I would say we should do the same...

**Comment by mthoren-adi** [comment]
> 

Is the legacy path pervasive among the drivers that we do control? ( https://wiki.analog.com/resources/tools-software/linux-drivers-all#hwmon_pmbus ) , or was the ADT7420 an anomaly?

**Comment by nunojsa** [comment]
> Is the legacy path pervasive among the drivers that we do control? ( https://wiki.analog.com/resources/tools-software/linux-drivers-all#hwmon_pmbus ) , or was the ADT7410/20 an anomaly?

Not really sure. But probably some older parts might have the same path. The point to me is that libiio should be agnostic to this if we want to fully support HWMON here.

**Comment by rgetz** [comment]
yeah, looks like libsensors pokes around a few places for things.

https://github.com/lm-sensors/lm-sensors/blob/master/lib/sysfs.c#L636-L638
https://github.com/lm-sensors/lm-sensors/blob/master/lib/sysfs.c#L118-L119
https://github.com/lm-sensors/lm-sensors/blob/master/lib/sysfs.c#L86-L87

sys/class/i2c-adapter/i2c-%d/device
sys/bus/i2c/devices
sys/class/hwmon
sys/class/i2c-adapter

**Comment by pcercuei** [comment]
I don't really think we need to support old deprecated APIs for drivers that aren't upstream.

**Comment by nunojsa** [comment]
> I don't really think we need to support old deprecated APIs for drivers that aren't upstream.

Well, the API is definitely deprecated but you do have considerable **upstream** drivers using it (including the ADI one @rgetz mentioned):

https://elixir.bootlin.com/linux/v5.15.8/A/ident/hwmon_device_register

I don't think the API is going away anytime soon unless someone really wants to have the effort to convert some old drivers to the new API.

Anyways, if we are going to take the position, "oh well let's convert the ADI drivers and just assume we do not support deprecated stuff in libiio", I would at least make that explicit either in the commit message or with a comment in the code [or maybe both].

Just my opinion...

**Comment by pcercuei** [comment]
@nunojsa the way I see it... Right now libiio doesn't support the old deprecated hwmon API either, so this PR does not *break* anything. Let's say it only adds support for a subset of hwmon devices (the ones with an up-to-date driver upstream), and if people want to add support for more hwmon devices, then they (or we) can update the related driver.

**Comment by nunojsa** [comment]
> Right now libiio doesn't support the old deprecated hwmon API either, so this PR does not break anything. Let's say it only adds support for a subset of hwmon devices (the ones with an up-to-date driver upstream), and if people want to add support for more hwmon devices, then they (or we) can update the related driver.

That's totally fair as long as we make it somewhere explicit that's the case :). So that no one comes complain that we do not support the old stuff...

**Comment by pcercuei** [comment]
@nunojsa I explicited it in the commit message and in the iio.h documentation as well.

**Review by nunojsa — APPROVED** [review]

**Comment by mthoren-adi** [comment]
@pcercuei I just rebuilt and checked this out on my experimenter board, and I'm still getting the same behavior connecting remotely vs. locally - the LM75 shows up fine locally:
```
	hwmon6: lm75
		1 channels found:
			temp1:  (input)
			3 channel-specific attributes found:
				attr  0: input value: 26500
				attr  1: max value: 80000
				attr  2: max_hyst value: 75000
		1 device-specific attributes found:
				attr  0: update_interval value: 100
		No trigger on this device
```
The ADT7420 exists, but no attributes shown (I believe this is expected, given the current state of the driver (https://github.com/analogdevicesinc/linux/pull/1647)

But when connecting remotely, only one of the temperature sensors exists at all, and its name is not being shown:
```
PS C:\Users\mthoren> iio_attr -d -u ip:experimenter.local
IIO context has 12 devices:
        hwmon0, cpu_thermal: found 0 device attributes
        hwmon1, rpi_volt: found 0 device attributes
        hwmon2, ltc2977: found 0 device attributes
        hwmon3, ltc2974: found 0 device attributes
        hwmon4, ltc3880: found 0 device attributes
        hwmon5: found 0 device attributes
```
The above is from Windows, latest libiio release, but the behavior is the same when I build the hwmon branch on a remote Linux machine.

Anything I should be trying?
Also note - not sure if this would make any difference but I manually edited CMakeLists.txt... I could not figure out how to pass the option in:
`option(WITH_HWMON "Add compatibility with the hardware monitoring (hwmon) subsystem" ON)`

**Comment by pcercuei** [comment]
@mthoren-adi sadly I can't reproduce :( All my hwmon devices and channels appear, I have zero differences between the two outputs.
Please double-check that the libiio and IIOD running on your target were built from the latest "hwmon" branch, maybe you are using some older build there?

**Comment by mnsgs** [comment]
Hi,

I stumbled upon this PR and finds it relevant for us. We have IIO drivers for most of our HW peripherals, with the exception of a few temperature sensors - being capable to abstract them all through iio is highly appreciated. However, we have a few instances of the same temperature sensor - output from lm-sensors:

```
root@nanomind-z7045-nv3:~# sensors
tmp100-i2c-2-1b
Adapter: xiic-i2c
temp1:        +34.2 C  (high = +80.0 C, hyst = +75.0 C)

tmp100-i2c-2-0a
Adapter: xiic-i2c
temp1:        +34.2 C  (high = +80.0 C, hyst = +75.0 C)

tmp100-i2c-1-4e
Adapter: Cadence I2C at e0005000
temp1:        +35.1 C  (high = +80.0 C, hyst = +75.0 C)

tmp100-i2c-2-12
Adapter: xiic-i2c
temp1:        +33.7 C  (high = +80.0 C, hyst = +75.0 C)

tmp401-i2c-1-4c
Adapter: Cadence I2C at e0005000
temp1:        +43.0 C  (low  =  +0.0 C, high = +85.0 C)
                       (crit = +85.0 C, hyst = +75.0 C)
temp2:        +53.4 C  (low  =  +0.0 C, high = +85.0 C)
                       (crit = +85.0 C, hyst = +75.0 C)

```

and queried through iio:

```
root@nanomind-z7045-nv3:~# iio_attr -d
IIO context has 40 devices:
        hwmon0, tmp100: found 1 device attributes
        hwmon1, tmp401: found 1 device attributes
        hwmon2, tmp100: found 1 device attributes
        hwmon3, tmp100: found 1 device attributes
        hwmon4, tmp100: found 1 device attributes
        iio:device0, ps_1v: found 2 device attributes
        iio:device1, ps_1v8: found 2 device attributes
        iio:device10, xadc: found 1 device attributes
        iio:device11, a_1v3-a: found 2 device attributes
        iio:device12, vcco_1v8-a: found 2 device attributes
        iio:device13, b_1v3-a: found 2 device attributes
        iio:device14, lna-a: found 2 device attributes
        iio:device15, vin-a: found 2 device attributes
        iio:device16, ad9361-phy-a: found 19 device attributes
.
.
.

```
I wonder whether it would be possible, through libiio, to name the hwmon devices similar to the approach of lm-sensors - i.e. <name>-<i2c-controller>-<i2c-address> and thus make each device name unique?

Thanks,
Martin

**Comment by pcercuei** [comment]
Hi @mnsgs,

First of all, the device name isn't meant to be unique, that's the purpose of the identifier.
The names are obtained from the kernel directly (through the "name" sysfs attribute), and I don't want to change that - libiio should just present the IIO/hwmon context as it is in sysfs.

In your case the kernel gives the same name to iio devices that represent different instances of the same hardware. Note that this problem exists in IIO as well. It can be solved there by specifying each device's nickname in the devicetree, through the "label" property. I think it would make sense to add a similar feature to the hwmon subsystem.

**Comment by mnsgs** [comment]
> Note that this problem exists in IIO as well. It can be solved there by specifying each device's nickname in the devicetree, through the "label" property. 

Yes, I am aware - we are actively using IIO labels for distinguishing HW peripherals abstracted as IIO devices. The issue relates solely to HW peripherals abstracted as HWMON devices. AFAIK, there is no "label" concept here - it relies on config files for this (https://linux.die.net/man/5/sensors.conf). It is my understanding that the config file parsing logic resides within 'sensors' application (https://github.com/lm-sensors/lm-sensors/blob/42f240d2a457834bcbdf4dc8b57237f97b5f5854/prog/sensors/main.c#L87). 

I assume the intention is not to duplicate this logic into libiio, it is however not clear to me whether there is another way to achieve this? Or if this "feature" at all is in scope of the planned libiio hwmon support?

**Comment by Demon000** [comment]
> @pcercuei I just rebuilt and checked this out on my experimenter board, and I'm still getting the same behavior connecting remotely vs. locally - the LM75 shows up fine locally:
> 
> ```
> 	hwmon6: lm75
> 		1 channels found:
> 			temp1:  (input)
> 			3 channel-specific attributes found:
> 				attr  0: input value: 26500
> 				attr  1: max value: 80000
> 				attr  2: max_hyst value: 75000
> 		1 device-specific attributes found:
> 				attr  0: update_interval value: 100
> 		No trigger on this device
> ```
> 
> The ADT7420 exists, but no attributes shown (I believe this is expected, given the current state of the driver ([analogdevicesinc/linux#1647](https://github.com/analogdevicesinc/linux/pull/1647))
> 
> But when connecting remotely, only one of the temperature sensors exists at all, and its name is not being shown:
> 
> ```
> PS C:\Users\mthoren> iio_attr -d -u ip:experimenter.local
> IIO context has 12 devices:
>         hwmon0, cpu_thermal: found 0 device attributes
>         hwmon1, rpi_volt: found 0 device attributes
>         hwmon2, ltc2977: found 0 device attributes
>         hwmon3, ltc2974: found 0 device attributes
>         hwmon4, ltc3880: found 0 device attributes
>         hwmon5: found 0 device attributes
> ```
> 
> The above is from Windows, latest libiio release, but the behavior is the same when I build the hwmon branch on a remote Linux machine.
> 
> Anything I should be trying? Also note - not sure if this would make any difference but I manually edited CMakeLists.txt... I could not figure out how to pass the option in: `option(WITH_HWMON "Add compatibility with the hardware monitoring (hwmon) subsystem" ON)`

In the process of adding debugfs_reg_access support to ADT7420, I also updated the driver to use `devm_hwmon_device_register_with_info` which will create the parameters in their proper place. https://github.com/analogdevicesinc/linux/pull/1770

**Comment by pcercuei** [comment]
@mnsgs what I'm saying is, we can update the kernel to add a "label" sysfs property to hwmon devices just like it's done with IIO.

**Comment by mnsgs** [comment]
@pcercuei , would that be a hwmon equivalent of https://github.com/analogdevicesinc/linux/commit/2c3d0c9ffd24d9b4c62c5dfb2104695a614be28c ? If so, I'd be glad to test it out.

**Comment by pcercuei** [comment]
@mnsgs yes, that's the plan - I'll work on a patch. Then we need a patch for libiio to use the "label" to override a device's name, and that should be good.

**Comment by pcercuei** [comment]
@mnsgs Could you try 4bd0e2d05b0e? If you add labels in the device tree, you should see "label" attributes appear in the hwmon devices.

Next step would be to handle the "label" attribute in libiio so that it overrides the device name.

**Comment by pcercuei** [comment]
@Demon000 could you test this patch too?

**Comment by Demon000** [comment]
> @Demon000 could you test this patch too?

Works.

**Comment by pcercuei** [comment]
Please test from commit https://github.com/analogdevicesinc/linux/commit/85d7b388b2af instead - I cleaned up the patch a bit, which is now much simpler.

**Comment by Demon000** [comment]
> Please test from commit [analogdevicesinc/linux@85d7b38](https://github.com/analogdevicesinc/linux/commit/85d7b388b2af) instead - I cleaned up the patch a bit, which is now much simpler.

Works x2.

**Comment by mnsgs** [comment]
@pcercuei , we are currently on the 2018_r2 hdl/linux baseline (thus Linux 4.14) and I thus had to port it back (`sysfs_emit` was replaced by `sprintf`.

The labels are added to the relevant devices according to:

```
tmp401@4c {
    compatible = "ti,tmp401";
    label = "temp_pcb_z7k";
    reg = <0x4c>;
};

tmp100@4e {
    compatible = "ti,tmp100";
    label = "temp_pcb_dock";
    reg = <0x4e>;
};
```

Output from sensors:

```
root@nanomind-z7045-nv3:~# sensors 
tmp100-i2c-1-4e
Adapter: Cadence I2C at e0005000
temp1:        +35.8 C  (high = +80.0 C, hyst = +75.0 C)

tmp401-i2c-1-4c
Adapter: Cadence I2C at e0005000
temp1:        +43.5 C  (low  =  +0.0 C, high = +85.0 C)
                       (crit = +85.0 C, hyst = +75.0 C)
temp2:        +58.7 C  (low  =  +0.0 C, high = +85.0 C)
                       (crit = +85.0 C, hyst = +75.0 C)
```

Kernel structure of the primary hwmon device:
```
root@nanomind-z7045-nv3:~# find /sys/class/hwmon/hwmon0/ -type f
/sys/class/hwmon/hwmon0/temp1_max
/sys/class/hwmon/hwmon0/update_interval
/sys/class/hwmon/hwmon0/power/runtime_suspended_time
/sys/class/hwmon/hwmon0/power/autosuspend_delay_ms
/sys/class/hwmon/hwmon0/power/runtime_active_time
/sys/class/hwmon/hwmon0/power/control
/sys/class/hwmon/hwmon0/power/runtime_status
/sys/class/hwmon/hwmon0/label
/sys/class/hwmon/hwmon0/temp1_max_hyst
/sys/class/hwmon/hwmon0/uevent
/sys/class/hwmon/hwmon0/temp1_input
/sys/class/hwmon/hwmon0/name
```

```
root@nanomind-z7045-nv3:~# cat /sys/class/hwmon/hwmon0/name 
tmp100
root@nanomind-z7045-nv3:~# cat /sys/class/hwmon/hwmon0/label 
temp_pcb_dock
```

For some reason the label appears not propagated for the second (tmp401) device though:
```
root@nanomind-z7045-nv3:~# find /sys/class/hwmon/hwmon1/ -type f
/sys/class/hwmon/hwmon1/temp1_max_alarm
/sys/class/hwmon/hwmon1/temp1_min
/sys/class/hwmon/hwmon1/temp1_max
/sys/class/hwmon/hwmon1/temp2_fault
/sys/class/hwmon/hwmon1/temp2_crit_hyst
/sys/class/hwmon/hwmon1/temp2_input
/sys/class/hwmon/hwmon1/temp2_min
/sys/class/hwmon/hwmon1/update_interval
/sys/class/hwmon/hwmon1/power/runtime_suspended_time
/sys/class/hwmon/hwmon1/power/autosuspend_delay_ms
/sys/class/hwmon/hwmon1/power/runtime_active_time
/sys/class/hwmon/hwmon1/power/control
/sys/class/hwmon/hwmon1/power/runtime_status
/sys/class/hwmon/hwmon1/temp1_min_alarm
/sys/class/hwmon/hwmon1/temp2_max_alarm
/sys/class/hwmon/hwmon1/temp2_crit
/sys/class/hwmon/hwmon1/temp2_max
/sys/class/hwmon/hwmon1/temp1_crit
/sys/class/hwmon/hwmon1/temp2_min_alarm
/sys/class/hwmon/hwmon1/temp1_crit_alarm
/sys/class/hwmon/hwmon1/uevent
/sys/class/hwmon/hwmon1/temp1_crit_hyst
/sys/class/hwmon/hwmon1/temp1_input
/sys/class/hwmon/hwmon1/name
/sys/class/hwmon/hwmon1/temp2_crit_alarm
```

```
root@nanomind-z7045-nv3:~# cat /sys/class/hwmon/hwmon1/name
tmp401
```

I'll try to see if I can find an explanation for this

**Comment by mnsgs** [comment]
I managed to get hold of a piece of HW with additional tmp100s mounted, and they seem all to propagate the label:

```
root@nanomind-z7045-nv3:~# find -L /sys/class/hwmon/ -maxdepth 2 -name label -print -exec cat {} \;
/sys/class/hwmon/hwmon2/label
temp_pcb_tr600-a
/sys/class/hwmon/hwmon0/label
temp_pcb_dock
```
Reading the data appears also fine:
```
root@nanomind-z7045-nv3:~# iio_attr -c temp_pcb_tr600-a temp1 input
47062

root@nanomind-z7045-nv3:~# sensors tmp100-i2c-2-0a
tmp100-i2c-2-0a
Adapter: xiic-i2c
temp1:        +47.1 C  (high = +80.0 C, hyst = +75.0 C)
```

I notice that tmp100 is based on the lm75 hwmon driver whereas the tmp4xx family has it's own - I'll keep digging...

**Comment by pcercuei** [comment]
@mnsgs following feedback from upstream developers on my first patchset, I prepared a revised version that I'm going to send soon, the new patch is https://github.com/analogdevicesinc/linux/commit/8062e21729b8

Could you check if you now get the label with your `tmp401` hwmon device?

**Comment by mthoren-adi** [comment]
@mnsgs , @Demon000 , could you see if you get the same behavior through the local vs. network backends? I've got multiple HWMON peripherals attached to a Raspberry Pi 4 (LTC2974, LTC2977, LTC3880, LM75, and ADT7420) - I always see everything locally (from iio_info, iio_attr), but when specifying -u ip:localhost on the Pi itself, or from a remote Windows machine, I am getting inconsistent results- some devices not showing up, and it's intermittent. I have yet to do an exhaustive test, but it would be good to know if others are seeing similar behavior.

**Comment by mnsgs** [comment]
@pcercuei this patch seems better :+1: :

```
root@nanomind-z7045-nv3:~# find -L /sys/class/hwmon/ -maxdepth 2 -name name -print -exec cat {} \;
/sys/class/hwmon/hwmon0/name
tmp100
/sys/class/hwmon/hwmon1/name
tmp401

root@nanomind-z7045-nv3:~# find -L /sys/class/hwmon/ -maxdepth 2 -name label -print -exec cat {} \;
/sys/class/hwmon/hwmon0/label
temp_pcb_dock
/sys/class/hwmon/hwmon1/label
temp_pcb_z7k
```

**Comment by mnsgs** [comment]
@mthoren-adi I do see the same hwmon devices over local vs. network:
```
$ ./iio_attr -u ip:192.168.30.2 -d
IIO context has 13 devices:
        hwmon0, temp_pcb_dock: found 1 device attributes
        hwmon1, temp_pcb_z7k: found 1 device attributes
        iio:device0, ps_1v: found 2 device attributes
        iio:device1, ps_1v8: found 2 device attributes
        iio:device10, xadc: found 1 device attributes
        iio:device2, ddr_1v35: found 2 device attributes
        iio:device3, ps_3v3: found 2 device attributes
        iio:device4, pl_1v: found 2 device attributes
        iio:device5, pl_1v8: found 2 device attributes
        iio:device6, extout_3v3: found 2 device attributes
        iio:device7, adj_2v5: found 2 device attributes
        iio:device8, vcc_main: found 2 device attributes
        iio:device9, v_clk_dist: found 2 device attributes
```

**Comment by mthoren-adi** [comment]
@mnsgs Thanks for checking - I am beginning to suspect something subtle, particular to my exact setup.

**Comment by mthoren-adi** [comment]
@pcercuei , @rgetz , a quick update on hardware testing here - I am getting reliable results over the network backend with a single ADT75, on Raspberry Pi Zero 2 W, 3B Plus, and 4 (1GB model). This is starting with a fresh Kuiper install, and not adding anything extra. Booted each of these setups at least 5 times, so far so good.

After adding the PowerStick (LTC2974, LTC2977, LTC3880) I seem to get reliable results with the RPi 3B+ and Zero 2 W, BUT - the LTC3880 and ADT74 do not show up over the network backend on Raspberry Pi 4. The Raspberry Pi 4 is the common element with all testing I'd done above, my larger hardware setup (with several other SPI, I2C peripherals) is based on RPi 4, 8GB model.

This does seem really strange - the fact that everything shows up over local backend sort of exonerates the I2C hardware, I would think.

**Comment by pcercuei** [comment]
@mthoren-adi I'm trying now with just the PowerStick, and the output of iio_info is the exact same on both the local and network backends. I do get the LTC3880, LTC2977, LTC2974.

**Comment by pcercuei** [comment]
@mthoren-adi your disappearing hwmon devices bug should be fixed by #777 and https://github.com/analogdevicesinc/linux_image_ADI-scripts/pull/29.

**Review by mthoren-adi — APPROVED** [review]

**Pull request merged**
