### PR TITLE
add bounds checking for errstr

### PR DESCRIPTION
**Pull request by camill8**
Add error checking to prevent buffer overrun in fixed length buffer.

### CODE REVIEW

**Comment by pcercuei** [comment]
Hi Charlie,

The patch looks good. Could you sign-off your commit (git commit -s)? We cannot accept it without.

**Review by pcercuei — CHANGES_REQUESTED** [review]
Signed-off-by: required.

**Comment by rgetz** [comment]
@camill8 : we will need to reject this if we don't get your signed-off-by soon.

Thanks for understanding.
-Robin

**Comment by rgetz** [comment]
Closing - due to inactivity

**Pull request closed without merging**
