### PR TITLE
tests: iio_attr: Add support for controlling the context timeout

### PR DESCRIPTION
**Pull request by mhennerich**
Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>

### CODE REVIEW

**Comment by rgetz** [comment]
shouldn't this be a common thing that is added to all utilities? (which is already in some of them)?

**Comment by mhennerich** [comment]
I think it now in all tools which requires it. 
Maybe we should also use the set value for codegen. There is already: 
void gen_context_timeout(unsigned int timeout_ms); 
which doesn't get used at all.

**Comment by rgetz** [comment]
yeah, its:

```
iio_readdev.c:	  {"timeout", required_argument, 0, 'T'},
iio_writedev.c:	  {"timeout", required_argument, 0, 'T'},
iio_stresstest.c:	{"timeout", required_argument, 0, 't'},
```

so, I think it makes sense to shuffle `iio_stresstest` to use `"T"` and move your patch to the common parts, and like you said - connect the gen_code parts... 

I can do that this afternoon if you want.

**Comment by mhennerich** [comment]
Sounds great - Thanks

**Comment by rgetz** [comment]
Ok - closing this.

**Pull request closed without merging**
